services:
  return-db:
    extends:
      file: docker-compose-base.yaml
      service: return-db
    ports:
      - 5432:5432
  return:
    extends:
      file: docker-compose-base.yaml
      service: return
    ports:
      - 8080:8080
  return-dapr:
    extends:
      file: docker-compose-base.yaml
      service: return-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
volumes:
  return-db-data: