services:
  return-db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - return-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=return
    healthcheck:
      test: pg_isready -U postgres -d return -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 3
  return:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://return-db:5432/return
      - SPRING_FLYWAY_URL=jdbc:postgresql://return-db:5432/return
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
    healthcheck:
      test: wget -qO - http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      return-db:
        condition: service_healthy
  return-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "return",
      "--app-port", "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:return"
volumes:
  return-db-data:
