spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://return-db:5432/return
  flyway:
    url: jdbc:postgresql://return-db:5432/return
    locations: classpath:db/migration
graphql:
  packages: org.misarch.return
  federation:
    enabled: true